# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.markdown_transformer:
        class: AppBundle\Service\MarkdownTransformer
        arguments: ['@markdown.parser', '@doctrine_cache.providers.markdown_cache']
    qpp.markdown_extension:
        class: AppBundle\Twig\MarkdownExtension
        #arguments: ['@app.markdown_transformer']
        autowire: true
        tags:
            - { name: twig.extension }